# Generated by Django 4.0.3 on 2022-04-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('kcal', models.CharField(max_length=10)),
                ('foodstuff', models.ManyToManyField(help_text='Select your foodstuff', to='web.foodstuff')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
