# Generated by Django 4.0.3 on 2022-04-16 21:05

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=web.models.picture_path, verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='kcal',
            field=models.CharField(max_length=10, verbose_name='Kcal'),
        ),
    ]
